name: Deploy web to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: web/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        # Write environment variables (from repo secrets) into a .env file so Vite injects them
        run: |
          if [ -n "${VITE_BACKEND_BASE}" ]; then echo "VITE_BACKEND_BASE=${VITE_BACKEND_BASE}" >> .env; fi
          if [ -n "${VITE_API_URL}" ]; then echo "VITE_API_URL=${VITE_API_URL}" >> .env; fi
          if [ -n "${VITE_FEEDBACK_URL}" ]; then echo "VITE_FEEDBACK_URL=${VITE_FEEDBACK_URL}" >> .env; fi
          if [ -n "${VITE_MODEL_URL}" ]; then echo "VITE_MODEL_URL=${VITE_MODEL_URL}" >> .env; fi
          echo "Generated .env for build:" && cat .env || true
          npm run build
        env:
          VITE_BACKEND_BASE: ${{ secrets.VITE_BACKEND_BASE }}
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_FEEDBACK_URL: ${{ secrets.VITE_FEEDBACK_URL }}
          VITE_MODEL_URL: ${{ secrets.VITE_MODEL_URL }}

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: web/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


